//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suaadabdu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class satış_yönetimiEntities : DbContext
    {
        public satış_yönetimiEntities()
            : base("name=satış_yönetimiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_login> Table_login { get; set; }
        public virtual DbSet<TB_CAT> TB_CAT { get; set; }
        public virtual DbSet<TB_Supp> TB_Supp { get; set; }
        public virtual DbSet<TB_PUR> TB_PUR { get; set; }
        public virtual DbSet<TB_cus> TB_cus { get; set; }
        public virtual DbSet<tb_sell> tb_sell { get; set; }
        public virtual DbSet<tb_users> tb_users { get; set; }
    }
}
