//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suaadabdu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PUR
    {
        public int ID { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> supp_id { get; set; }
        public string pur_name { get; set; }
        public string pur_type { get; set; }
        public string pur_cat { get; set; }
        public string pur_supp { get; set; }
        public string pur_det { get; set; }
        public Nullable<double> pur_buy { get; set; }
        public Nullable<double> pur_set { get; set; }
        public Nullable<double> pur_qu { get; set; }
        public Nullable<double> pur_tset { get; set; }
        public Nullable<double> pur_tbuy { get; set; }
        public Nullable<double> pur_tpro { get; set; }
    
        public virtual TB_CAT TB_CAT { get; set; }
        public virtual TB_Supp TB_Supp { get; set; }
    }
}
