//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suaadabdu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Supp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Supp()
        {
            this.TB_PUR = new HashSet<TB_PUR>();
        }
    
        public int ID { get; set; }
        public string supp_name { get; set; }
        public string supp_phone { get; set; }
        public string supp_email { get; set; }
        public byte[] supp_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PUR> TB_PUR { get; set; }
    }
}
