//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suaadabdu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_users
    {
        public int ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASS { get; set; }
        public string USER_ROL { get; set; }
        public string USER_STATE { get; set; }
    }
}
